<?php

$utenti = [
    // 25 minorenni (12-17 anni)
    ["nome" => "Luca01", "cognome" => "Rossi01", "eta" => 15, "citta" => "Roma"],
    ["nome" => "Marco02", "cognome" => "Bianchi02", "eta" => 16, "citta" => "Milano"],
    ["nome" => "Giulia03", "cognome" => "Verdi03", "eta" => 14, "citta" => "Napoli"],
    ["nome" => "Anna04", "cognome" => "Neri04", "eta" => 13, "citta" => "Torino"],
    ["nome" => "Paolo05", "cognome" => "Gialli05", "eta" => 12, "citta" => "Palermo"],
    ["nome" => "Sara06", "cognome" => "Blu06", "eta" => 17, "citta" => "Roma"],
    ["nome" => "Davide07", "cognome" => "Ferrari07", "eta" => 16, "citta" => "Milano"],
    ["nome" => "Elena08", "cognome" => "Romano08", "eta" => 15, "citta" => "Napoli"],
    ["nome" => "Simone09", "cognome" => "Esposito09", "eta" => 13, "citta" => "Torino"],
    ["nome" => "Chiara10", "cognome" => "Ricci10", "eta" => 12, "citta" => "Palermo"],
    ["nome" => "Alessio11", "cognome" => "Marino11", "eta" => 14, "citta" => "Roma"],
    ["nome" => "Martina12", "cognome" => "Greco12", "eta" => 17, "citta" => "Milano"],
    ["nome" => "Francesco13", "cognome" => "Bruno13", "eta" => 12, "citta" => "Napoli"],
    ["nome" => "Valentina14", "cognome" => "Gallo14", "eta" => 13, "citta" => "Torino"],
    ["nome" => "Matteo15", "cognome" => "Conti15", "eta" => 15, "citta" => "Palermo"],
    ["nome" => "Federica16", "cognome" => "DeLuca16", "eta" => 16, "citta" => "Roma"],
    ["nome" => "Andrea17", "cognome" => "Mancini17", "eta" => 14, "citta" => "Milano"],
    ["nome" => "Laura18", "cognome" => "Lombardi18", "eta" => 13, "citta" => "Napoli"],
    ["nome" => "Stefano19", "cognome" => "Moretti19", "eta" => 12, "citta" => "Torino"],
    ["nome" => "Irene20", "cognome" => "Barbieri20", "eta" => 17, "citta" => "Palermo"],
    ["nome" => "Giorgio21", "cognome" => "Fontana21", "eta" => 16, "citta" => "Roma"],
    ["nome" => "Alessandra22", "cognome" => "Santoro22", "eta" => 15, "citta" => "Milano"],
    ["nome" => "Riccardo23", "cognome" => "Rinaldi23", "eta" => 14, "citta" => "Napoli"],
    ["nome" => "Beatrice24", "cognome" => "Caruso24", "eta" => 13, "citta" => "Torino"],
    ["nome" => "Daniele25", "cognome" => "Ferrara25", "eta" => 12, "citta" => "Palermo"],

    // 25 maggiorenni (18-69 anni)
    ["nome" => "Camilla26", "cognome" => "Galli26", "eta" => 35, "citta" => "Roma"],
    ["nome" => "Emanuele27", "cognome" => "Martini27", "eta" => 46, "citta" => "Milano"],
    ["nome" => "Noemi28", "cognome" => "Leone28", "eta" => 47, "citta" => "Napoli"],
    ["nome" => "Fabio29", "cognome" => "Longo29", "eta" => 48, "citta" => "Torino"],
    ["nome" => "Serena30", "cognome" => "Gentile30", "eta" => 49, "citta" => "Palermo"],
    ["nome" => "Claudio31", "cognome" => "Martinelli31", "eta" => 50, "citta" => "Roma"],
    ["nome" => "Arianna32", "cognome" => "Vitale32", "eta" => 51, "citta" => "Milano"],
    ["nome" => "Cristian33", "cognome" => "Testa33", "eta" => 52, "citta" => "Napoli"],
    ["nome" => "Marta34", "cognome" => "Fiore34", "eta" => 53, "citta" => "Torino"],
    ["nome" => "Roberto35", "cognome" => "Pellegrini35", "eta" => 54, "citta" => "Palermo"],
    ["nome" => "Veronica36", "cognome" => "Basile36", "eta" => 55, "citta" => "Roma"],
    ["nome" => "Samuele37", "cognome" => "Silvestri37", "eta" => 56, "citta" => "Milano"],
    ["nome" => "Ginevra38", "cognome" => "Farina38", "eta" => 57, "citta" => "Napoli"],
    ["nome" => "Tommaso39", "cognome" => "Rizzo39", "eta" => 58, "citta" => "Torino"],
    ["nome" => "Aurora40", "cognome" => "Grassi40", "eta" => 59, "citta" => "Palermo"],
    ["nome" => "Nicola41", "cognome" => "Parisi41", "eta" => 60, "citta" => "Roma"],
    ["nome" => "Gloria42", "cognome" => "Villa42", "eta" => 61, "citta" => "Milano"],
    ["nome" => "Massimo43", "cognome" => "Coppola43", "eta" => 62, "citta" => "Napoli"],
    ["nome" => "Silvia44", "cognome" => "DeSantis44", "eta" => 63, "citta" => "Torino"],
    ["nome" => "Antonio45", "cognome" => "Orlando45", "eta" => 64, "citta" => "Palermo"],
    ["nome" => "Eleonora46", "cognome" => "Ruggiero46", "eta" => 65, "citta" => "Roma"],
    ["nome" => "Pietro47", "cognome" => "Marchetti47", "eta" => 66, "citta" => "Milano"],
    ["nome" => "Linda48", "cognome" => "Bellini48", "eta" => 67, "citta" => "Napoli"],
    ["nome" => "Salvatore49", "cognome" => "Serra49", "eta" => 68, "citta" => "Torino"],
    ["nome" => "Caterina50", "cognome" => "Fabbri50", "eta" => 69, "citta" => "Palermo"],
];

?>